In [ ]:
1)ans:
database:-A database is a collection of data that is organized, which is also called structured data. It
can be accessed or stored in a computer system. It can be managed through a Database Management System (DBMS),
a software used to manage data. Database refers to related data in a structured form.
SQL VS NONSQL
1)	Databases are categorized as Relational Database Management System (RDBMS).	
2)	SQL databases have fixed or static or predefined schema.	
3)	SQL databases display data in form of tables so it is known as table-based database.
4)	SQL databases are vertically scalable.	
5)	SQL databases use a powerful language "Structured Query Language" to define and manipulate the data.	
6)	SQL databases are best suited for complex queries.
7)	SQL databases are not best suited for hierarchical data storage.
8)	MySQL, Oracle, Sqlite, PostgreSQL and MS-SQL etc. are the example of SQL database.

1)	NoSQL databases are categorized as Non-relational or distributed database system.
2)	NoSQL databases have dynamic schema.
3)	NoSQL databases display data as collection of key-value pair, documents, graph databases or wide-column 
    stores.
4)	NoSQL databases are horizontally scalable.
5)	In NoSQL databases, collection of documents are used to query the data. It is also called unstructured query
    language. It varies from database to database.
6)	NoSQL databases are not so good for complex queries because these are not as powerful as SQL queries.
7)	NoSQL databases are best suited for hierarchical data storage.
8)	MongoDB, BigTable, Redis, RavenDB, Cassandra, Hbase, Neo4j, CouchDB etc. are the example of nosql database

In [ ]:
2)ans:
DDL stands for Data Definition Language. 
These commands are used to change the structure of a database and database objects.For example, DDL commands can
be used to add, remove, or modify tables with in a database.

The DDL commands are: 
1. CREATE : 
-This command is used to create table in the relational database . 
-This can be done by specifying the names and datatypes of various columns. 

2. ALTER : 
Alter command is used for altering the table in many forms like: 

-Add a column
-Rename existing column
-Drop a column
-Modify the size of the column or change datatype of the column

3. TRUNCATE : 
This command removes all the records from a table. But this command will not destroy the table’s structure. 

4. DROP
This command completely removes the table from the database along with the destruction of the table

In [ ]:
3)ans:
DML stands for Data Manipulation Language. Tables and formulas are helpful when communicating with data stored 
up to a point in a database through SQL (Structured Query Language), but a time comes when we actually want to 
execute some fairly complicated data interactions. We will also need the Data Manipulation Language in that 
situation. DML is a way to inform a database precisely what we want it to do by conversing in a manner that it 
has been built to comprehend from scratch. When it comes to interacting with existing data, whether adding, 
moving, or deleting data, it provides a convenient way to do so.

1-SELECT COMMAND
This command is used to get data out of the database. It helps users of the database to access from an operating
system, the significant data they need. It sends a track result set from one tables or more.

2-INSERT Command
This command is used to enter the information or values into a row. We can connect one or more records to a 
single table within a repository using this instruction. This is often used to connect an unused tag to the 
documents.

3-UPDATE Command
This command is used to alter existing table records. Within a table, it modifies data from one or more 
records. This command is used to alter the data which is already present in a table

4-DELETE Command
It deletes all archives from a table. This command is used to erase some or all of the previous table’s records.
If we do not specify the ‘WHERE’ condition then all the rows would be erased or deleted.

In [ ]:
4)ans:
Data Query Language is used to perform queries against the data stored in a relational database.

DQL includes the SELECT statement, as well as a variety of operators and functions that can be used to manipulate
the retrieved data. The SELECT statement is typically used to retrieve data from one or more database tables, 
and it can contain various clauses that specify the exact data to retrieve as well as how it is presented when 
it’s returned.

In [ ]:
5)ans:
What is Primary Key?
A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values.
It is either an existing table column or a column that is specifically generated by the database according to a 
defined sequence. 

Example: STUD_NO, as well as STUD_PHONE both, are candidate keys for relation STUDENT but STUD_NO can be chosen
as the primary key (only one out of many candidate keys). 

What is Foreign Key?
A foreign key is a column or group of columns in a relational database table that provides a link between data 
in two tables. It is a column (or columns) that references a column (most often the primary key) of another
table. 

Example: STUD_NO in STUDENT_COURSE is a foreign key to STUD_NO in STUDENT relation.

In [ ]:
6)ans:
python code to connect mysql:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
print(mydb)
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")

cursor:-Allows Python code to execute PostgreSQL command in a database session. Cursors are created by the 
connection.cursor() method: they are bound to the connection for the entire lifetime and all the commands are 
executed in the context of the database session wrapped by the connection.

Method cursor.execute ():
The execute () method helps us to execute the query and return records according to the query

In [ ]:
7)ans
Order	Clause	Function
1	FROM	-Tables are joined to get the base data.
2	WHERE	-The base data is filtered.
3	GROUP BY	-The filtered base data is grouped.
4	HAVING	-The grouped base data is filtered.
5	SELECT	-The final data is returned.
6	ORDER BY	-The final data is sorted.
7	LIMIT	-The returned data is limited to row count.